### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by BrunoMSantos** [msabramo/requests-unixsocket#20]
I do have git installed, but installation fails with following message:
```
$ python setup.py build
[...]
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /tmp/yaourt-tmp-bruno/aur-python-requests-unixsocket/src/requests-unixsocket-0.1.5/setup.cfg: Exception: Versioning for this project
 requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
```

It installs correctly through pip though..

This is on an Arch x86_64 machine.

**Comment by msabramo** [comment]
What version of git do you have? And what does `git log -n 1` say?

**Comment by msabramo** [comment]
Going to close for now; will reopen if we can reproduce this.

**Comment by msabramo** [comment]
@BrunoMSantos: Is this still happening to you?

**Comment by BrunoMSantos** [comment]
Sorry for neglecting this, I never *really* used this package and somehow must have missed notification of your other post.
I quickly checked just now and it works fine.

**Comment by msabramo** [comment]
Oh no worries as I also took a long time to respond. I'm glad it's working!
