### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by anders-was-here** [msabramo/requests-unixsocket#38]
In Python 3.7 async is a reserved word. See: https://docs.python.org/3.4/library/asyncio-task.html#asyncio.async

I needed to replace half a dozen instances of 'asyncio.async' with 'asyncio.ensure_future'
to make it work.

Like:
```
-        asyncio.async(self._get_and_publish_event_log(), loop=self._event_loop)
+        asyncio.ensure_future(self._get_and_publish_event_log(), loop=self._event_loop)
```

**Comment by msabramo** [comment]
Hmmm, I just ran Python 3.7 tests in tox and it passed. Also, I didn't find any instance of `async` in the code on `master`. Can you clarify?

**Comment by anders-was-here** [comment]
Either it's fixed for it was posted to the wrong Github project.
