### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by olemoign** [msabramo/requests-unixsocket#48]
Hi,
the last release is pretty old and I can see changes in the main module, could you make a new release?
Thank you!

**Comment by TomGoBravo** [comment]
The 0.2.0 release was in Aug 2019. It looks like it just missed the fix for https://github.com/msabramo/requests-unixsocket/issues/37 . Do you see anything else missing from it?

**Comment by olemoign** [comment]
Sorry, as the 0.2.0 isn't tagged here, I didn't see it.
