### ISSUE TITLE
Release with PR #42

### ISSUE THREAD

**Issue by TomGoBravo** [msabramo/requests-unixsocket#49]
https://files.pythonhosted.org/packages/4d/ce/78b651fe0adbd4227578fa432d1bde03b4f4945a70c81e252a2b6a2d895f/requests-unixsocket-0.2.0.tar.gz doesn't seem to contain kwargs in `UnixAdapter.__init__` so I think it doesn't include https://github.com/msabramo/requests-unixsocket/pull/42/files which is the fix for https://github.com/msabramo/requests-unixsocket/issues/37. Could you release a new version with the fix?
Thank you.

**Comment by yifeireplay** [comment]
we need this release as well, thanks!

**Comment by msabramo** [comment]
(Finally) released https://pypi.org/project/requests-unixsocket/0.3.0/

Sorry for the delay!
