### ISSUE TITLE
0.2.0 tag missing

### ISSUE THREAD

**Issue by mgorny** [msabramo/requests-unixsocket#50]
Pypi indicates that the newest version is 0.2.0. However, the newest tag in this repo is 0.1.5. Could you add the missing tag?

**Comment by kloczek** [comment]
Yes please add missing git tag.
My automation relies on git tags :(

**Comment by SuperSandro2000** [comment]
Ping

**Comment by msabramo** [comment]
Sorry for the delay, I just pushed the tag:

https://github.com/msabramo/requests-unixsocket/releases/tag/0.2.0

**Comment by kloczek** [comment]
Now looks lile 0.3.0 tag is missing :p

Nevertheless .. thank you :)
