### ISSUE TITLE
GET parameters stripped from URL

### ISSUE THREAD

**Issue by mminer** [msabramo/requests-unixsocket#6]
In a request like `http+unix://%2Fvar%2Frun%2Fdocker.sock/containers/nginx/logs?timestamp=true`, the GET parameters at the end of the URL are stripped out. This is due to `UnixHTTPConnection.request` only passing through the URL's path to its parent function ([relevant line of code](https://github.com/msabramo/requests-unixsocket/blob/8d692622c9466fcf3d7d4c1c190c7aaf84267c1e/requests_unixsocket/adapters.py#L31)).

The problem is easily fixed by removing the aforementioned line or by removing `UnixHTTPConnection.request` entirely. I'd issue a pull request, but I'm unsure of the motivation behind the current behaviour and want to avoid inadvertently breaking other requests.

**Comment by phobologic** [comment]
I ran into the same issue, and I'd be curious about the reasoning behind it as well.

**Comment by msabramo** [comment]
Thanks for pointing this out. No reasoning; I simply forgot. I will accept a PR...

**Comment by msabramo** [comment]
I'm going to go ahead and work on this now.

**Comment by phobologic** [comment]
For reference, the dockerpy code has something similar to this (without the constraint you're looking at here):

https://github.com/docker/docker-py/blob/master/docker/unixconn/unixconn.py
